- clean: ['~']

- link:
    ~/.axelrc: axelrc
    ~/.bowerrc: .bowerrc
    ~/.csslintrc: csslintrc
    ~/.dotfiles: ''
    ~/.editorconfig: .editorconfig
    ~/.eslintrc: .eslintrc
    ~/.gitconfig: .gitconfig
    ~/.gitconfig: gitconfig
    ~/.gitignore_global: gitignore_global
    ~/.jshintrc: jshintrc
    ~/.lesskey: lesskey
    ~/.npmrc: .npmrc
    ~/.oh-my-zsh: .oh-my-zsh/
    ~/.rtorrent.rc: rtorrent.rc
    ~/.screenrc: screenrc
    ~/.tmux.conf: tmux.conf
    ~/.vim: vim/
    ~/.vimrc: vimrc
    ~/.zsh: zsh/
    ~/.zshrc: zshrc

- shell:
  -
    - mkdir -p ~/.rtorrent/session ~/.rtorrent/watch ~/.rtorrent/downloads
    - Creating rtorrent directories
  -
    - git submodule update --recursive
    - Updating submodules
