- clean: ['~']

- link:
    ~/dotfiles/oh-my-custom/themes/cobalt2.zsh-theme: iTerm2/Cobalt2-iterm/cobalt2.zsh-theme
    ~/.axelrc: axelrc.conf
    ~/.bowerrc: bowerrc.js
    ~/.csslintrc: csslintrc.js
    ~/.dircolors: dircolors-solarized/dircolors.256dark
    ~/.dotfiles: ''
    ~/.editorconfig: editorconfig.conf
    ~/.esformatter: esformatter.json
    ~/.eslintrc: eslintrc.js
    ~/.gitconfig: gitconfig.conf
    ~/.gitignore_global: gitignore_global.conf
    ~/.jshintrc: jshintrc.js
    ~/.lesskey: lesskey.conf
    ~/.npmrc: npmrc.ini
    ~/.nvmrc: nvmrc.conf
    ~/.oh-my-zsh: .oh-my-zsh/
    ~/.rtorrent.rc: rtorrent.rc.conf
    ~/.screenrc: screenrc.conf
    ~/.stylelint: stylelint.js
    ~/.tmux: tmux.conf
    ~/.vim: vim/
    ~/.vimrc: vimrc.conf
    ~/.yo-rc-global.json: yo-rc-global.json
    ~/.zsh: zsh/
    ~/.zshrc: zshrc.conf

- shell:
  -
    - mkdir -p ~/.rtorrent/session ~/.rtorrent/watch ~/.rtorrent/downloads
    - Creating rTorrent directories
