[color]
  ui = auto
[color "grep"]
  match = cyan bold
  selected = blue
  context = normal
  filename = magenta
  linenumber = green
  separator = yellow
  function = blue
[pretty]
  line = "%C(auto)%h%d %s %C(yellow)by %C(blue)%an %C(green)%ar"
  compact = "%C(auto)%h %s %C(green)%ar%n %C(auto)%d%n"
  detail = "%C(auto)%h %s%n  %C(yellow)by %C(blue)%an %C(magenta)<%ae> [%G?] %C(green)%ar%n %C(auto)%d%n"
[merge]
  defaultToUpstream = true
  tool = vimdiff
[mergetool]
  keepBackup = false
[push]
  default = upstream
[credential]
  helper = cache --timeout=3600
[grep]
  lineNumber = true
[advice]
  detachedHead = false
[core]
  # BUG: SourceTree https://jira.atlassian.com/browse/SRCTREEWIN-2398
  commentChar = "#"
  excludesFile = ~/.gitignore_global

# Allow local customizations in the .gitconfig_local file
[include]
  path = ~/.gitconfig_local
[difftool "sourcetree"]
  cmd = opendiff \"$LOCAL\" \"$REMOTE\"
  path =
[mergetool "sourcetree"]
  cmd = /Applications/SourceTree.app/Contents/Resources/opendiff-w.sh \"$LOCAL\" \"$REMOTE\" -ancestor \"$BASE\" -merge \"$MERGED\"
  trustExitCode = true
[url "https://"]
  insteadOf = git://

# User
[user]
  name = Marek Kaczkowski
  email = marek.kaczkowski@gmail.com
[commit]
  template = ~/.stCommitMsg
