# Allow local customizations in the ~/.zshrc_local_before file
if [ -f ~/.zshrc_local_before ]; then
    source ~/.zshrc_local_before
fi

# External plugins (initialized before)
source ~/.zsh/plugins_before.zsh

# Settings
source ~/.zsh/settings.zsh

# Bootstrap
source ~/.zsh/bootstrap.zsh

# External settings
source ~/.zsh/external.zsh

# Aliases
source ~/.zsh/aliases.zsh

# External plugins (initialized after)
source ~/.zsh/plugins_after.zsh

# Allow local customizations in the ~/.zshrc_local_after file
if [ -f ~/.zshrc_local_after ]; then
  source ~/.zshrc_local_after
fi

# RVM
# export PATH="$HOME/.rbenv/bin:$PATH"
# if which rbenv > /dev/null; then
#   eval "$(rbenv init -)";
# fi

# NVM
# XXX Don't use nvm zsh plugin
export NVM_DIR="$HOME/.nvm"
. "/usr/local/opt/nvm/nvm.sh"

# NPM
export PATH="`npm config get prefix`/lib/node_modules:$PATH"
export NODE_PATH="$NODE_PATH:`npm root -g`"

# Yarn bin is at /usr/local/bin
# Yarn global
# export PATH="$PATH:`yarn global bin`"

# React Expo XDE
EXPONENT_EDITOR="sublime"

# tabtab source for yarn package
# uninstall by removing these lines or running `tabtab uninstall yarn`
[[ -f /Users/marekkaczkowski/.nvm/versions/node/v6.11.4/lib/node_modules/yarn-completions/node_modules/tabtab/.completions/yarn.zsh ]] && . /Users/marekkaczkowski/.nvm/versions/node/v6.11.4/lib/node_modules/yarn-completions/node_modules/tabtab/.completions/yarn.zsh
