"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](color_yellow)\
$os\
$username\
[](bg:color_yellow2 fg:color_yellow)\
$directory\
[](fg:color_yellow2 bg:color_green)\
$git_branch\
$git_status\
[](fg:color_green bg:color_green2)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:color_green2 bg:color_bg2)\
$docker_context\
$conda\
[](fg:color_bg2 bg:color_bg1)\
$time\
[ ](fg:color_bg1)\
$line_break$character"""

palette = 'everforest'

[palettes.everforest]
color_fg0 = '#d3c6aa'
color_fg1 = '#272e32'
color_bg1 = '#21272b'
color_bg2 = '#272e32'
color_red = '#e67e81'
color_orange = '#e69875'
color_yellow = '#dbbc7f'
color_yellow2 = '#b99e68'
color_green = '#a7c080'
color_green2 = '#8ca36a'
color_blue = '#7fbbb3'
color_blue2 = '#699e97'
color_aqua = '#83c092'
color_purple = '#d699b6'
color_purple2 = '#785767'

[os]
disabled = false
style = "bg:color_yellow fg:color_fg1"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
Pop = ""

[username]
show_always = true
style_user = "bg:color_yellow fg:color_fg1"
style_root = "bg:color_yellow fg:color_fg1"
format = '[ $user ]($style)'

[directory]
style = "fg:color_fg1 bg:color_yellow2"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:color_green"
format = '[[ $symbol $branch ](fg:color_fg1 bg:color_green)]($style)'

[git_status]
style = "bg:color_green"
format = '[[($all_status$ahead_behind )](fg:color_fg1 bg:color_green)]($style)'

[nodejs]
symbol = ""
style = "bg:color_green2"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_green2)]($style)'

[c]
symbol = " "
style = "bg:color_green2"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_green2)]($style)'

[rust]
symbol = ""
style = "bg:color_green2"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_green2)]($style)'

[golang]
symbol = ""
style = "bg:color_green2"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_green2)]($style)'

[php]
symbol = ""
style = "bg:color_green2"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_green2)]($style)'

[java]
symbol = ""
style = "bg:color_green2"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_green2)]($style)'

[kotlin]
symbol = ""
style = "bg:color_green2"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_green2)]($style)'

[haskell]
symbol = ""
style = "bg:color_green2"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_green2)]($style)'

[python]
symbol = ""
style = "bg:color_green2"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_green2)]($style)'

[docker_context]
symbol = ""
style = "bg:color_bg2"
format = '[[ $symbol( $context) ](fg:#83a598 bg:color_bg2)]($style)'

[conda]
style = "bg:color_bg2"
format = '[[ $symbol( $environment) ](fg:#83a598 bg:color_bg2)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:color_bg1"
format = '[[  $time ](fg:color_fg0 bg:color_bg1)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:color_green)'
error_symbol = '[](bold fg:color_red)'
vimcmd_symbol = '[](bold fg:color_green)'
vimcmd_replace_one_symbol = '[](bold fg:color_yellow)'
vimcmd_replace_symbol = '[](bold fg:color_yellow)'
vimcmd_visual_symbol = '[](bold fg:color_yellow)'
