name: shellcheck
on:
  workflow_dispatch:
    
  push:
    paths:
      - "**/*.sh"
    branches:
      - "main"
jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    container: koalaman/shellcheck-alpine:v0.8.0
    steps:
      - uses: actions/checkout@v3
      - name: Check shell scripts
        run: shellcheck -S warning -a -x dot_env_setup/executable_install.sh
